import { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Cat Food",
    slug: "premium-cat-food",
    description: "Nutritious and balanced food for adult cats.",
    price: 1200,
    category: "cat",
    image: "https://img.drz.lazcdn.com/static/bd/p/95b1ff16b6525d9153f35f09a8e38b73.jpg_720x720q80.jpg",
    stock: 20,
    rating: 4.5,
    brand: "MeowPlus",
  },
  {
    id: "2",
    name: "Dog Chew Toy",
    slug: "dog-chew-toy",
    description: "Durable chew toy for healthy teeth and gums.",
    price: 650,
    category: "dog",
    image: "https://m.media-amazon.com/images/I/71BSLKDOeyL.jpg",
    stock: 35,
    rating: 4.2,
    brand: "PawPlay",
  },
  {
    id: "3",
    name: "Bird Seed Mix",
    slug: "bird-seed-mix",
    description: "Natural seed mix for all pet birds.",
    price: 450,
    category: "bird",
    image: "https://static-01.daraz.com.bd/p/601f6f37eaa6d42f4fd67412f3ab90cf.jpg",
    stock: 50,
    rating: 4.6,
    brand: "FeatherCare",
  },
  {
    id: "4",
    name: "Fish Tank Filter",
    slug: "fish-tank-filter",
    description: "High-performance filter for clean aquarium water.",
    price: 2200,
    category: "fish",
    image: "https://img.drz.lazcdn.com/static/bd/p/850a89e4890de94ba765e67893de6507.jpg_720x720q80.jpg",
    stock: 10,
    rating: 4.4,
    brand: "AquaLife",
  },
  {
    id: "5",
    name: "Pet Multivitamin Syrup",
    slug: "pet-multivitamin-syrup",
    description: "Daily multivitamin syrup for overall pet health.",
    price: 980,
    category: "other",
    image: "https://petzonebd.com/wp-content/uploads/2024/10/Petup-Pro-Syrup-For-Cats-Dogs-Pet-Health-Supplements.webp",
    stock: 25,
    rating: 4.7,
    brand: "VetPlus",
  },
];
