import { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Cat Food",
    slug: "premium-cat-food",
    description: "Nutritious and balanced food for adult cats.",
    price: 1200,
    category: "cat",
    image: "/images/products/cat-food.png",
    stock: 20,
    rating: 4.5,
    brand: "MeowPlus",
  },
  {
    id: "2",
    name: "Dog Chew Toy",
    slug: "dog-chew-toy",
    description: "Durable chew toy for healthy teeth and gums.",
    price: 650,
    category: "dog",
    image: "/images/products/dog-toy.png",
    stock: 35,
    rating: 4.2,
    brand: "PawPlay",
  },
  {
    id: "3",
    name: "Bird Seed Mix",
    slug: "bird-seed-mix",
    description: "Natural seed mix for all pet birds.",
    price: 450,
    category: "bird",
    image: "/images/products/bird-food.png",
    stock: 50,
    rating: 4.6,
    brand: "FeatherCare",
  },
  {
    id: "4",
    name: "Fish Tank Filter",
    slug: "fish-tank-filter",
    description: "High-performance filter for clean aquarium water.",
    price: 2200,
    category: "fish",
    image: "/images/products/fish-filter.png",
    stock: 10,
    rating: 4.4,
    brand: "AquaLife",
  },
  {
    id: "5",
    name: "Pet Multivitamin Syrup",
    slug: "pet-multivitamin-syrup",
    description: "Daily multivitamin syrup for overall pet health.",
    price: 980,
    category: "other",
    image: "/images/products/pet-vitamin.png",
    stock: 25,
    rating: 4.7,
    brand: "VetPlus",
  },
];
