// import { Product } from "@/types/product";

// export const products: Product[] = [
//   {
//     id: "1",
//     name: "Premium Cat Food",
//     slug: "premium-cat-food",
//     description: "Nutritious and balanced food for adult cats.",
//     price: 1200,
//     category: "cat",
//     image: "https://img.drz.lazcdn.com/static/bd/p/95b1ff16b6525d9153f35f09a8e38b73.jpg_720x720q80.jpg",
//     stock: 20,
//     rating: 4.5,
//     brand: "MeowPlus",
//   },
//   {
//     id: "2",
//     name: "Dog Chew Toy",
//     slug: "dog-chew-toy",
//     description: "Durable chew toy for healthy teeth and gums.",
//     price: 650,
//     category: "dog",
//     image: "https://m.media-amazon.com/images/I/71BSLKDOeyL.jpg",
//     stock: 35,
//     rating: 4.2,
//     brand: "PawPlay",
//   },
//   {
//     id: "3",
//     name: "Bird Seed Mix",
//     slug: "bird-seed-mix",
//     description: "Natural seed mix for all pet birds.",
//     price: 450,
//     category: "bird",
//     image: "https://static-01.daraz.com.bd/p/601f6f37eaa6d42f4fd67412f3ab90cf.jpg",
//     stock: 50,
//     rating: 4.6,
//     brand: "FeatherCare",
//   },
//   {
//     id: "4",
//     name: "Fish Tank Filter",
//     slug: "fish-tank-filter",
//     description: "High-performance filter for clean aquarium water.",
//     price: 2200,
//     category: "fish",
//     image: "https://img.drz.lazcdn.com/static/bd/p/850a89e4890de94ba765e67893de6507.jpg_720x720q80.jpg",
//     stock: 10,
//     rating: 4.4,
//     brand: "AquaLife",
//   },
//   {
//     id: "5",
//     name: "Pet Multivitamin Syrup",
//     slug: "pet-multivitamin-syrup",
//     description: "Daily multivitamin syrup for overall pet health.",
//     price: 980,
//     category: "other",
//     image: "https://petzonebd.com/wp-content/uploads/2024/10/Petup-Pro-Syrup-For-Cats-Dogs-Pet-Health-Supplements.webp",
//     stock: 25,
//     rating: 4.7,
//     brand: "VetPlus",
//   },
// ];

import { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Cat Food",
    slug: "premium-cat-food",
    description: "Nutritious and balanced food for adult cats. Supports healthy digestion and shiny coat.",
    price: 1200,
    category: "cat",
    image: "https://img.drz.lazcdn.com/static/bd/p/95b1ff16b6525d9153f35f09a8e38b73.jpg_720x720q80.jpg",
    stock: 20,
    rating: 4.5,
    brand: "MeowPlus",
    createdAt: "2024-01-15",
    tags: ["food", "dry", "adult"],
    discount: 10
  },
  {
    id: "2",
    name: "Dog Chew Toy",
    slug: "dog-chew-toy",
    description: "Durable chew toy for healthy teeth and gums. Made from natural rubber.",
    price: 650,
    category: "dog",
    image: "https://m.media-amazon.com/images/I/71BSLKDOeyL.jpg",
    stock: 35,
    rating: 4.2,
    brand: "PawPlay",
    createdAt: "2024-02-20",
    tags: ["toy", "chew", "dental"],
    discount: 0
  },
  {
    id: "3",
    name: "Bird Seed Mix",
    slug: "bird-seed-mix",
    description: "Natural seed mix for all pet birds. Contains sunflower, millet, and oats.",
    price: 450,
    category: "bird",
    image: "https://static-01.daraz.com.bd/p/601f6f37eaa6d42f4fd67412f3ab90cf.jpg",
    stock: 50,
    rating: 4.6,
    brand: "FeatherCare",
    createdAt: "2024-01-05",
    tags: ["food", "seeds", "natural"],
    discount: 5
  },
  {
    id: "4",
    name: "Fish Tank Filter",
    slug: "fish-tank-filter",
    description: "High-performance filter for clean aquarium water. Suitable for 50-100L tanks.",
    price: 2200,
    category: "fish",
    image: "https://img.drz.lazcdn.com/static/bd/p/850a89e4890de94ba765e67893de6507.jpg_720x720q80.jpg",
    stock: 10,
    rating: 4.4,
    brand: "AquaLife",
    createdAt: "2024-03-10",
    tags: ["filter", "equipment", "tank"],
    discount: 15
  },
  {
    id: "5",
    name: "Pet Multivitamin Syrup",
    slug: "pet-multivitamin-syrup",
    description: "Daily multivitamin syrup for overall pet health. Suitable for cats and dogs.",
    price: 980,
    category: "health",
    image: "https://petzonebd.com/wp-content/uploads/2024/10/Petup-Pro-Syrup-For-Cats-Dogs-Pet-Health-Supplements.webp",
    stock: 25,
    rating: 4.7,
    brand: "VetPlus",
    createdAt: "2024-02-28",
    tags: ["health", "supplement", "vitamins"],
    discount: 0
  },
  {
    id: "6",
    name: "Cat Scratching Post",
    slug: "cat-scratching-post",
    description: "Tall scratching post with hanging toy. Saves furniture and provides exercise.",
    price: 1800,
    category: "cat",
    image: "https://m.media-amazon.com/images/I/61h+YD37BHL._AC_UF894,1000_QL80_.jpg",
    stock: 15,
    rating: 4.3,
    brand: "CatHaven",
    createdAt: "2024-03-15",
    tags: ["furniture", "toy", "scratch"],
    discount: 20
  },
  {
    id: "7",
    name: "Dog Bed Large",
    slug: "dog-bed-large",
    description: "Orthopedic memory foam bed for large breed dogs. Waterproof cover included.",
    price: 3200,
    category: "dog",
    image: "https://cdn.thewirecutter.com/wp-content/media/2023/10/dog-beds-2048px-9727.jpg",
    stock: 8,
    rating: 4.8,
    brand: "ComfyPaws",
    createdAt: "2024-02-10",
    tags: ["bed", "furniture", "comfort"],
    discount: 12
  },
  {
    id: "8",
    name: "Bird Cage Deluxe",
    slug: "bird-cage-deluxe",
    description: "Large stainless steel cage with multiple perches and feeding stations.",
    price: 4500,
    category: "bird",
    image: "https://m.media-amazon.com/images/I/71YqK-TwqFL.jpg",
    stock: 5,
    rating: 4.1,
    brand: "FeatherCare",
    createdAt: "2024-01-20",
    tags: ["cage", "furniture", "housing"],
    discount: 8
  },
  {
    id: "9",
    name: "Aquarium Heater",
    slug: "aquarium-heater",
    description: "Automatic heater with temperature control for tropical fish.",
    price: 1500,
    category: "fish",
    image: "https://m.media-amazon.com/images/I/61hJSqJjALL._AC_UF1000,1000_QL80_.jpg",
    stock: 18,
    rating: 4.0,
    brand: "AquaLife",
    createdAt: "2024-03-05",
    tags: ["heater", "equipment", "tropical"],
    discount: 10
  },
  {
    id: "10",
    name: "Pet Grooming Kit",
    slug: "pet-grooming-kit",
    description: "Complete grooming kit with brushes, nail clippers, and shampoo.",
    price: 1250,
    category: "health",
    image: "https://cdn.thewirecutter.com/wp-content/media/2023/10/petgroomingkit-2048px-0247.jpg",
    stock: 30,
    rating: 4.4,
    brand: "PetCarePro",
    createdAt: "2024-02-15",
    tags: ["grooming", "kit", "care"],
    discount: 0
  },
  {
    id: "11",
    name: "Cat Litter Box",
    slug: "cat-litter-box",
    description: "Automatic self-cleaning litter box with odor control.",
    price: 5800,
    category: "cat",
    image: "https://m.media-amazon.com/images/I/61-nQ3KlHOL.jpg",
    stock: 6,
    rating: 4.6,
    brand: "SmartCat",
    createdAt: "2024-03-01",
    tags: ["litter", "hygiene", "automatic"],
    discount: 25
  },
  {
    id: "12",
    name: "Dog Leash & Harness Set",
    slug: "dog-leash-harness-set",
    description: "Reflective leash with padded harness for safe walks.",
    price: 850,
    category: "dog",
    image: "https://m.media-amazon.com/images/I/71N9h-pTccL.jpg",
    stock: 40,
    rating: 4.5,
    brand: "WalkSafe",
    createdAt: "2024-01-30",
    tags: ["leash", "harness", "walking"],
    discount: 5
  },
  {
    id: "13",
    name: "Fish Food Flakes",
    slug: "fish-food-flakes",
    description: "Nutritionally complete food flakes for all tropical fish.",
    price: 380,
    category: "fish",
    image: "https://m.media-amazon.com/images/I/51eGNSxQk2L.jpg",
    stock: 45,
    rating: 4.2,
    brand: "AquaLife",
    createdAt: "2024-02-25",
    tags: ["food", "flakes", "tropical"],
    discount: 0
  },
  {
    id: "14",
    name: "Rabbit Hutch",
    slug: "rabbit-hutch",
    description: "Spacious outdoor hutch with weatherproof roof and run area.",
    price: 4200,
    category: "other",
    image: "https://cdn.media.amplience.net/i/petsathome/Rabbit-Hutch-Run-5ft-x-2ft",
    stock: 7,
    rating: 4.3,
    brand: "BunnyHome",
    createdAt: "2024-01-12",
    tags: ["hutch", "housing", "outdoor"],
    discount: 15
  },
  {
    id: "15",
    name: "Pet Carrier Bag",
    slug: "pet-carrier-bag",
    description: "Ventilated carrier bag for small pets with safety lock.",
    price: 1600,
    category: "other",
    image: "https://m.media-amazon.com/images/I/61Ylmk-5v5L.jpg",
    stock: 22,
    rating: 4.7,
    brand: "TravelPet",
    createdAt: "2024-03-18",
    tags: ["carrier", "travel", "bag"],
    discount: 10
  },
  {
    id: "16",
    name: "Cat Treats Salmon",
    slug: "cat-treats-salmon",
    description: "Grain-free salmon treats for training and rewards.",
    price: 550,
    category: "cat",
    image: "https://m.media-amazon.com/images/I/61Tflpt4WxL.jpg",
    stock: 60,
    rating: 4.8,
    brand: "MeowPlus",
    createdAt: "2024-02-05",
    tags: ["treats", "food", "salmon"],
    discount: 0
  },
  {
    id: "17",
    name: "Dog Dental Treats",
    slug: "dog-dental-treats",
    description: "Dental chews that reduce plaque and freshen breath.",
    price: 720,
    category: "dog",
    image: "https://m.media-amazon.com/images/I/61hHTuXhN9L.jpg",
    stock: 55,
    rating: 4.4,
    brand: "DentalDog",
    createdAt: "2024-01-25",
    tags: ["treats", "dental", "chews"],
    discount: 8
  },
  {
    id: "18",
    name: "Small Animal Cage",
    slug: "small-animal-cage",
    description: "Multi-level cage for hamsters, gerbils, and other small pets.",
    price: 2900,
    category: "other",
    image: "https://m.media-amazon.com/images/I/81a8bPwfB2L.jpg",
    stock: 12,
    rating: 4.0,
    brand: "TinyPaws",
    createdAt: "2024-03-08",
    tags: ["cage", "housing", "small"],
    discount: 20
  },
  {
    id: "19",
    name: "Water Fountain for Pets",
    slug: "water-fountain-pets",
    description: "Automatic water fountain encouraging pets to drink more.",
    price: 1900,
    category: "health",
    image: "https://m.media-amazon.com/images/I/61z-q+HvZJL.jpg",
    stock: 25,
    rating: 4.6,
    brand: "HydraPet",
    createdAt: "2024-02-18",
    tags: ["fountain", "water", "health"],
    discount: 12
  },
  {
    id: "20",
    name: "Pet First Aid Kit",
    slug: "pet-first-aid-kit",
    description: "Comprehensive first aid kit for pet emergencies.",
    price: 1350,
    category: "health",
    image: "https://m.media-amazon.com/images/I/71C5cHDrJUL.jpg",
    stock: 15,
    rating: 4.9,
    brand: "SafetyPet",
    createdAt: "2024-01-08",
    tags: ["first aid", "emergency", "health"],
    discount: 0
  }
];